version: "3.8"
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: medusaDB
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
    ports:
      - "5432:5432"
    networks:
      - hmpps_int

  wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps_int
    container_name: wiremock
    restart: always
    ports:
      - "9091:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    command: --verbose

networks:
  hmpps_int:

#  medusa:
#    build: .
#    ports:
#      - "9000:9000"
#    environment:
#      DATABASE_URL: postgres://medusa:medusa@postgres:5432/medusaDB
#      REDIS_URL: redis://redis:6379
#      JWT_SECRET: supersecret
#      COOKIE_SECRET: supersecret
#    depends_on:
#      - postgres
#      - redis
#
#  redis:
#    image: redis
