generic-service:
  nameOverride: hmpps-digital-canteen-medusa-service
  productId: "DPS128"

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-digital-canteen-medusa-service
    tag: app_version # override at deployment time
    port: 9000

  livenessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

  readinessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-digital-canteen-medusa-cert

  env:
    NODE_ENV: "production"
    PORT: "9000"

  namespace_secrets:
    medusa-secrets:
      JWT_SECRET: "jwt-secret"
      COOKIE_SECRET: "cookie-secret"
      ADMIN_EMAIL: "admin-email"
      ADMIN_PASSWORD: "admin-password"
    rds-postgresql-instance-output:
      DB_SERVER: "rds_instance_address"
      DB_NAME: "database_name"
      DB_USER: "database_username"
      DB_PASSWORD: "database_password"
    hmpps-digital-canteen-api-client-creds:
      SYSTEM_CLIENT_ID: 'API_CLIENT_ID'
      SYSTEM_CLIENT_SECRET: 'API_CLIENT_SECRET'

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-digital-canteen-medusa-service
